### PR TITLE
Out of bounds fixes.

### PR DESCRIPTION
**Pull request by mrigger**
I found several out-of-bounds accesses using AFL that are fixed by the changes in this PR.

### CODE REVIEW

**Comment by kokke** [comment]
hi @mrigger and thanks a lot for providing these awesome fixes :)

I am curious to learn how you have utilized AFL to find these bugs - would it be possible to see the driver code / scaffolding?

I know AFL but have only dabbled with it for half an hour.
From my understanding, you need to get AFL to crash the program.
How did you trigger the crashes on out-of-bounds accesses?
Did you build with clang memory sanitizer or something like that?

I don't like the call to `fputs` since it won't work on a lot of embedded target, however the call can easily be replaced with a macro or something else.

Again thank you very much for contributing the fix as well as the bug report. I am very grateful :)

**Comment by mrigger** [comment]
No problem! I'm glad that you merged the PR!

Here is the AFL driver that I used:
```c
#include <stdio.h>
#include "re.h"

int main() {
    char buf[100];
    char text[100];
    re_t pattern;
    fgets(buf, 100, stdin);
    fgets(text, 100, stdin);
    pattern = re_compile(buf);
    re_matchp(pattern, text);
}
```
I started with a single input for fuzzing:
```
[a*3?!]
hello
```

AFL discovered the first two or so bugs by crashing the binary. When it did not find more errors, I coupled AFL with the AddressSanitizer.

**Comment by kokke** [comment]
Thanks for providing the driver code as well :)

When I wrote this code I had a feeling it would be difficult to verify if I was doing out of bounds accesses. I couldn't think of a good way of testing it that didn't require me spending a lot of time analyzing each case.

AFL combined with clang sanitizers are an excellent way to automatically test for these bugs. Thanks a lot for the great inspiration Manuel 👍

**Comment by kokke** [comment]
Hey if you make a PR that adds some AFL fuzzing to the tests, I'll gladly merge that as well :)

Maybe it could be added as a separate target in the Makefile such that people that don't have AFL installed could still run the tests.

**Pull request merged**
