### PR TITLE
Modified `?` to be greedy

### PR DESCRIPTION
**Pull request by ToriningenGames**
In response to your comment in issue #36, I changed the logic for `?`, making it greedy like all other operators. This is congruent with Python's implementation.

I also updated the C portion of the test suite to accommodate, and added a few extra cases to ensure `?` was working correctly. Like previously, the Python generator I did not touch (I do not know Python comfortably enough), but it should not be affected.

Documentation has been updated. Conveniently, the code compiles smaller now. I deleted the mention that recursive could be compiled over iterative with a preprocessor flag because that is not the case: the recursive code is `#if 0`'d out of existence.

I may try poking branches (`|`) next, but sadly I'm almost certain the code size would grow above 500 lines. :(

### CODE REVIEW

**Comment by ToriningenGames** [comment]
I implemented branches (`|`) in a separate branch (VCS change line)

I must say I'm disappointed with the result. It can only work meaningfully, and be reasonably implemented, if it behaves differently from Python. The binary size is now 3.5 kB. The code looks more complicated.

I am confident these things cannot be fixed for branches, and groups cannot be implemented, unless the regex parsing produces an actual parse tree, as opposed to the 2 level pseudo-tree it does now. To do that, would require pointer shenanigans turning the linear buffer into the nonlinear tree, and I don't think that's what you have in mind for small, clear code.

For these reasons, I don't feel like issuing a pull request for it.

**Comment by kokke** [comment]
Hi @ToriningenGames and thanks again for your big contribution to the project :)

I'll review the changes in `?` - hopefully later this evening.


I agree with regards to branches and quantifiers - they are not easy to implement under the current architecture.

I think it would be possible to encode a richer set of operators without turning to a full regex tree, if the compile-step used e.g. a 32-bit integer array instead of the current 2x8 bit array. 

What @monolifed has done in https://github.com/monolifed/tiny-regex-mod is somewhat similar, adding more "bits" to encode the quantification -- he has changed the the regex_t struct from:

```C
typedef struct regex_t
{
  unsigned char  type;   /* CHAR, STAR, etc.                      */
  union
  {
    unsigned char  ch;   /*      the character itself             */
    unsigned char* ccl;  /*  OR  a pointer to characters in class */
  };
} regex_t;
```

to

```C
typedef struct tre_node tre_node;
typedef struct tre_comp tre_comp;

struct tre_node
{
	unsigned char  type;
	union
	{
		char  ch;    // character
		char *cc;    // character class buffer
		unsigned short mn[2]; // {m,n} quantifier
	} u;
};

struct tre_comp
{
	tre_node nodes[TRE_MAX_NODES];
	char buffer[TRE_MAX_BUFLEN];
};
```

**Comment by kokke** [comment]
> I may try poking branches (|) next, but sadly I'm almost certain the code size would grow above 500 lines. :(


By the way, the 500 line thing is not a firm limit.

It doesn't really matter how many lines the project takes up.

I just think there is a point where a library stops being small/tiny/lightweight and easy to comprehend - and I don't want my projects to reach that point. Keeping code complexity and number of lines of code relatively low, is a good means to that end.

My motivation is to get a lot of functionality from a small code base that's fairly easy to hack on. I don't think 

I still agree with you though w.r.t. groups and branches, that we should instead strive to make changes in `re_compile` and start using a better-fitting data-structure for the problem.

**Comment by kokke** [comment]
Working great for me - thanks for the contribution @ToriningenGames :+1:

**Pull request closed without merging**
