### PR TITLE
fix: dot should not accept line terminators

### PR DESCRIPTION
**Pull request by ahmetkosker**

### CODE REVIEW

**Comment by kokke** [comment]
Hi @ahmetkosker - and thanks for your contribution :+1: 

Many implementations let you choose if DOT should accept newlines using a flag or some sort of option. I have thought about putting this choice into a macro, so it gets determined at compile time.

Most testing is done on single-line strings, so it shouldn't affect the current situation much.

I will try and see if I can get something tested tonight, and then I'll get back to you.

**Comment by kokke** [comment]
I made this commit: https://github.com/kokke/tiny-regex-c/commit/41d14b1968262dca58306d843cbf1ec828e5cc3f

... making it optional whether or not to match newline chars with the dot-operator.

Does that work for you @ahmetkosker  :) ?

**Comment by Nable80** [comment]
Hi @kokke 
``MATCES`` in ``RE_DOT_MATCES_NEWLINE`` looks like a typo. Did you mean ```MATC**H**ES`?

**Comment by kokke** [comment]
Hi @Nable80 - yes that is totally a typo, thanks for catching it and letting me know :)

How did I miss that yesterday :D

**Pull request merged**
